# Generated by Django 4.2.4 on 2023-08-29 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chassi_code', models.CharField(max_length=17)),
                ('license_plate', models.CharField(max_length=7)),
                ('base', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
                ('is_avaiable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ParamedicEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ambulance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paramedics', to='ambulance.ambulanceentity')),
            ],
        ),
    ]
