# Generated by Django 4.2.4 on 2023-09-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance', '0002_rename_ambulance_id_paramedicentity_ambulance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulanceentity',
            name='type',
            field=models.CharField(choices=[('a', 'Ambuância de Suporte Básico'), ('b', 'Ambuância de Suporte Médio'), ('c', 'Ambuância de Suporte Avançado')], max_length=100),
        ),
    ]
